node:
  extends:
    file: docker-compose-base.yml
    service: node
  environment:
    NODE_ENV: localdocker
    STATIC_ASSET_BASE:
    AJAX_BASE:
  links:
   - api
api:
  extends:
    file: docker-compose-base.yml
    service: api
  environment:
    SCALA_ENV: localdocker
  links:
    - db
db:
  extends:
    file: docker-compose-base.yml
    service: db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: p4ssw0rd