node:
  extends:
    file: docker-compose-base.yml
    service: node
  environment:
    NODE_ENV: localdocker
    STATIC_ASSET_BASE:
    AJAX_BASE:
    IP:
  dockerfile: local.dockerfile
  volumes:
    - frontend/:/usr/src/app
  links:
    - api
  ports:
    - "2992:2992"
    - "3000:3000"
api:
  extends:
    file: docker-compose-base.yml
    service: api
  environment:
    SCALA_ENV: localdocker
  dockerfile: local.dockerfile
  volumes:
    - ./backend/:/usr/src/app/
    - ~/.ivy2/:/root/.ivy2/
  links:
    - db
  ports:
    - "8080:8080"
db:
  extends:
    file: docker-compose-base.yml
    service: db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: p4ssw0rd
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data/:/var/lib/postgresql/data/