node:
  extends:
    file: docker-compose-base.yml
    service: node
  dockerfile: local.dockerfile
  volumes:
    - ./frontend/:/usr/src/app
    - ./backend/target/graphql/:/usr/src/backend/target/graphql
  links:
    - api
  expose:
    - "2992"
  ports:
    - "2992:2992"
    - "3000:3000"
  environment:
    - STATIC_ASSET_BASE
    - AJAX_BASE
    - NODE_ENV=localdocker
api:
  extends:
    file: docker-compose-base.yml
    service: api
  environment:
    - SCALA_ENV=localdocker
  dockerfile: local.dockerfile
  volumes:
    - ./backend/:/usr/src/app/
    - /usr/src/app/target/
    - /usr/src/app/project/target/
    - /usr/src/app/project/project/target/
    - ~/.ivy2/:/root/.ivy2/
  links:
    - db
  expose:
    - "8081"
  ports:
    - "8081:8081"
    - "8000:8000"
db:
  extends:
    file: docker-compose-base.yml
    service: db
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: p4ssw0rd
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data/:/var/lib/postgresql/data/
